### ISSUE TITLE
Kingpin Injector

### ISSUE THREAD

**Issue by rmills963** [Kamikaze94/WolfHUD#278]
Activating the injector from kingpin immediately crashes my game

**Comment by FlamingFox911** [comment]
This bug was already fixed a long time ago.

Please download the latest version of WolfHud [here](https://github.com/Kamikaze94/WolfHUD/archive/master.zip).
https://github.com/Kamikaze94/WolfHUD/issues/275#issuecomment-301322959

Let us know if it works. Otherwise, please post your crash log found at "%localappdata%\PAYDAY 2"

**Comment by rmills963** [comment]
I already got the latest version before posting. I installed the one from your link and still crash. 
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1002454/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/1002453/crashlog.txt)

**Comment by FlamingFox911** [comment]
Hmmm, I can't seem to replicate the issue. Judging from the error, it is coming from the Buff List settings.

**Comment by rmills963** [comment]
Injector duration buff setting didn't change anything. The error has more to it, now 
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1002708/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/1002709/crashlog.txt)

**Comment by FlamingFox911** [comment]
Just deducing the problem: Do you have your Kingpin perk maxed?

**Comment by rmills963** [comment]
No, I think 6 cards

**Comment by Lagmobile** [comment]
Just confirming I also get the crash. I've tried turning the Injector buff option on and off and I also only have 4 of 9 perks unlocked. Still getting the crash.

**Comment by FlamingFox911** [comment]
I have my perk maxed, and I don't get the crashed. Perhaps there is something wrong with the buff value when you don't have a full deck.

**Comment by Lagmobile** [comment]
Temporary fix: Turning off the buff list entirely stops it from crashing on injector use. All other settings are default. Hopefully that's helpful in some way.
